image: composer
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer install --no-dev
          - composer dump-autoload -o
        artifacts:
          - composer.json
          - composer.lock
          - vendor/**
